services:
  db:
    image: mysql:latest
    container_name: pirayesh_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: heydar1234
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s


  web:
    restart: always
    build: .
    volumes:
      - web_data:/app  # Volume برای فایل‌های وب (کد پروژه)
        - staticfiles:/app/staticfiles  # Volume برای فایل‌های استاتیک
        - mediafiles:/app/mediafiles
    ports:
      - "8000:8005"
    env_file:
      - .env
    depends_on:
      - db
    image: pirayesh
    container_name: pirayesh_container
    command: >
      sh -c "
            python wait_for_db.py &&
            python manage.py migrate &&
            ls -la &&
            ls -la pirayesh &&
            gunicorn pirayesh.wsgi:application --bind 0.0.0.0:8005 --workers 4 --threads 2  
            "
#    command: ["python", "manage.py", "runserver", "0.0.0.0:8005"]

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}


  nginx:
    image: nginx:latest
    container_name: pirayesh_nginx
    ports:
      - "8000:80"  # نکسین به پورت 80 داخل کانتینر گوش می‌ده
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app  # برای دسترسی Nginx به staticfiles و media
    depends_on:
      - web
  volumes:
    dbs_data: { }  # تعریف volume
volumes:
  db_data: {}
  web_data: {}  # Volume برای کد پروژه
  staticfiles: {}  # Volume برای فایل‌های استاتیک
  mediafiles: {}