# Generated by Django 4.2 on 2025-04-29 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=750)),
                ('time_excepted', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_off', models.BooleanField(default=False)),
                ('off', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(upload_to='haircuts/')),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hall_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=5020)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=12)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(to='service.hallimage')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('time_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.time')),
                ('experience', models.CharField(max_length=750)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled')], default='waiting', max_length=50)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('service.time',),
        ),
    ]
